networks:
  # Prepared for proxy
  web:
    external: true


services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./dist:/usr/share/nginx/html:ro
    labels:
      traefik.enable: true
      traefik.http.routers.pastitude.rule: Host(`mc-config.nobin.dev`)
      traefik.http.routers.pastitude.entryPoints: https
    networks:
      - web
